// Generated by CodiumAI

describe('submitData', () => {

    // Sends a POST request to the specified URL with the correct headers and body
    it('should send a POST request with the correct headers and body', () => {
      // Mock the fetch function
      global.fetch = jest.fn().mockImplementation(() => {
        return Promise.resolve({
          json: () => Promise.resolve({ id: 1 })
        });
      });

      // Call the submitData function
      submitData('Steve', 'steve@steve.com');

      // Check if fetch was called with the correct arguments
      expect(fetch).toHaveBeenCalledWith('http://localhost:3000/users', {
        method: 'POST',
        headers: {
          'Accept': 'application/json',
          'content-type': 'application/json'
        },
        body: JSON.stringify({
          name: 'Steve',
          email: 'steve@steve.com'
        })
      });
    });


});
